name: Package Application with Pyinstaller

on: 
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Package Application
      uses: walmis/pyinstaller-action-windows@main
      with:
        path: .
       
    - uses: actions/upload-artifact@v3
      with:
        name: build
        path: dist/windows/VPforce-TelemFFB
        
    - name: Make Zip
      id: zip
      run: |
        cd dist/windows/VPforce-TelemFFB && zip -r ../../../VPforce-TelemFFB .
        echo "::set-output name=tag_name::$(git tag --sort version:refname | tail -n 1)"
        
    - name: Deploy to Server
      uses: easingthemes/ssh-deploy@main
      env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-v"
          SOURCE: "VPforce-TelemFFB.zip"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.REMOTE_TARGET }}
          #EXCLUDE: "/dist/, /node_modules/"
